databases:
  - name: perpdb
    databaseName: perp_production
    user: perp_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: perp_web
    runtime: image
    image:
      url: ghcr.io/tillsc/perp_web:latest
    plan: free
    region: frankfurt
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PERP_DATABASE_ADAPTER
        value: postgresql
      - key: LOG_TO_STDOUT
        value: true
      - key: INITIAL_ADMIN_EMAIL
        value: admin@localhost
      - key: INITIAL_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: perpdb
          property: connectionString
